youtube_data = [
    {'name': 'T-Series', 'subscriber_count': 269, 'description': 'Music label and film production company', 'country': 'India'},
    {'name': 'MrBeast', 'subscriber_count': 288, 'description': 'Entertainment & philanthropy videos', 'country': 'United States'},
    {'name': 'SET India', 'subscriber_count': 167, 'description': 'TV channel - Hindi shows & drama', 'country': 'India'},
    {'name': 'Zee Music Company', 'subscriber_count': 116, 'description': 'Music label', 'country': 'India'},
    {'name': 'Goldmines', 'subscriber_count': 85, 'description': 'South Indian Hindi dubbed movies', 'country': 'India'},
    {'name': 'Colors TV', 'subscriber_count': 70, 'description': 'Entertainment TV channel', 'country': 'India'},
    {'name': 'Shemaroo Filmi Gaane', 'subscriber_count': 65, 'description': 'Bollywood song channel', 'country': 'India'},
    {'name': 'Aaj Tak', 'subscriber_count': 57, 'description': 'News channel', 'country': 'India'},
    {'name': 'BB Ki Vines', 'subscriber_count': 25, 'description': 'Comedy sketches', 'country': 'India'},
    {'name': 'CarryMinati', 'subscriber_count': 42, 'description': 'Comedy and roasting', 'country': 'India'},
    {'name': 'Round2hell', 'subscriber_count': 34, 'description': 'Comedy group', 'country': 'India'},
    {'name': 'Total Gaming', 'subscriber_count': 38, 'description': 'Gaming (Free Fire)', 'country': 'India'},
    {'name': 'Ashish Chanchlani Vines', 'subscriber_count': 31, 'description': 'Comedy and skits', 'country': 'India'},
    {'name': 'JKK Entertainment', 'subscriber_count': 29, 'description': 'Local skits and drama', 'country': 'India'},
    {'name': 'Trakin Tech', 'subscriber_count': 14, 'description': 'Tech reviews in Hindi', 'country': 'India'},
    {'name': 'Techno Gamerz', 'subscriber_count': 38, 'description': 'Gaming (GTA)', 'country': 'India'},
    {'name': 'FactTechz', 'subscriber_count': 17, 'description': 'Science and facts in Hindi', 'country': 'India'},
    {'name': 'Slayy Point', 'subscriber_count': 8.5, 'description': 'Funny commentary and internet culture', 'country': 'India'},
    {'name': 'MostlySane', 'subscriber_count': 7.2, 'description': 'Comedy & lifestyle by Prajakta Koli', 'country': 'India'},
    {'name': 'Niharika NM', 'subscriber_count': 2.2, 'description': 'Relatable comedy content', 'country': 'India'},
    {'name': 'Komal Pandey', 'subscriber_count': 1.3, 'description': 'Fashion & beauty', 'country': 'India'},
    {'name': 'Anaysa', 'subscriber_count': 10, 'description': 'DIY skincare & beauty', 'country': 'India'},
    {'name': 'Cook With Nisha', 'subscriber_count': 9.4, 'description': 'Indian cooking channel', 'country': 'India'},
    {'name': 'Village Cooking Channel', 'subscriber_count': 21, 'description': 'Traditional Indian village recipes', 'country': 'India'},
    {'name': 'A2 Motivation', 'subscriber_count': 21, 'description': 'Motivational content', 'country': 'India'},
    {'name': 'Stephanie Soo', 'subscriber_count': 3.3, 'description': 'Mukbang & true crime', 'country': 'South Korea / USA'},
    {'name': 'Korean Englishman', 'subscriber_count': 5.9, 'description': 'Korean culture & food with guests', 'country': 'UK / Korea'},
    {'name': 'Liziqi', 'subscriber_count': 17.6, 'description': 'Traditional Chinese village life', 'country': 'China'},
    {'name': 'PewDiePie', 'subscriber_count': 111, 'description': 'Gaming and comedy', 'country': 'Sweden'},
    {'name': 'Kids Diana Show', 'subscriber_count': 122, 'description': 'Kids’ entertainment', 'country': 'Ukraine / USA'},
    {'name': 'Like Nastya', 'subscriber_count': 112, 'description': 'Kids’ content and learning', 'country': 'Russia / USA'},
    {'name': 'Sandeep Maheshwari', 'subscriber_count': 29, 'description': 'Motivational speaker', 'country': 'India'},
    {'name': 'Flying Beast', 'subscriber_count': 9.3, 'description': 'Vlogs and fitness', 'country': 'India'},
    {'name': 'BeerBiceps (Ranveer Allahbadia)', 'subscriber_count': 5.2, 'description': 'Self-growth, interviews', 'country': 'India'},
    {'name': 'Dhruv Rathee', 'subscriber_count': 20.1, 'description': 'Educational & political commentary', 'country': 'India'},
    {'name': 'Triggered Insaan', 'subscriber_count': 21, 'description': 'Comedy and reaction videos', 'country': 'India'},
    {'name': 'Make Joke Of', 'subscriber_count': 10.5, 'description': 'Animated comedy sketches', 'country': 'India'},
    {'name': 'The Viral Fever (TVF)', 'subscriber_count': 13, 'description': 'Web series and comedy sketches', 'country': 'India'},
    {'name': 'Mumbiker Nikhil', 'subscriber_count': 4, 'description': 'Travel vlogs and lifestyle', 'country': 'India'},
    {'name': 'Technical Guruji', 'subscriber_count': 22.8, 'description': 'Tech videos in Hindi', 'country': 'India'},
    {'name': 'Tanya Khanijow', 'subscriber_count': 1.3, 'description': 'Travel vlogs', 'country': 'India'},
]
